Basic template
rancerenly/web-analysis-site pull request #15
Opened 2024-10-31 19:22 UTC by mrskycriper

Close https://github.com/rancerenly/web-analysis-site/issues/4
Close https://github.com/rancerenly/web-analysis-site/issues/6
Close https://github.com/rancerenly/web-analysis-site/issues/7
Close https://github.com/rancerenly/web-analysis-site/issues/8
Close https://github.com/rancerenly/web-analysis-site/issues/9

2024-10-31 19:53 UTC, rancerenly requested changes

2024-10-31 19:53 UTC, rancerenly commented on src/components/theme-switcher/index.tsx
> +    switch (theme) {
сделай мапу, а не свич-кейс. тут конечно маленький пример, но в общем лучше использовать мапу для таких ситуаций, а если тема не передана возвращай дефолтное значение

2024-10-31 19:53 UTC, rancerenly commented on src/components/theme-switcher/index.tsx
> +          style={{ margin: "0 1px", width: "16px" }}
можешь просто класс какой-нибудь накинуть кастомный свой, назвав обобщенно, вместо инлайн стилей

2024-10-31 19:53 UTC, rancerenly commented on src/components/theme-switcher/index.tsx
> +type ColorScheme = "light" | "dark";
вынеси типы в отдельный файл interfaces.ts или types.ts

2024-10-31 19:53 UTC, rancerenly commented on src/components/theme-switcher/index.tsx
> +  return ["auto", "light", "dark"].includes(value);
массив можно вынести в константу

2024-10-31 19:53 UTC, rancerenly commented on src/components/theme-switcher/index.tsx
> +function isOfTheme(value: string): value is Theme {
можно вынеси в файл helpers. лучше использовать стрелочные функции

2024-10-31 19:53 UTC, rancerenly commented on src/components/footer/index.tsx
> +function Footer() {
тоже как стрелочную функцию

2024-10-31 19:53 UTC, rancerenly commented on src/components/theme-switcher/index.tsx
> +    const value = localStorage.getItem("color-theme");
можешь тут сразу кастить тип value as Theme

2024-10-31 19:53 UTC, rancerenly commented on public/images/itmo-logo-dark.svg
можно в папку assets

2024-10-31 19:53 UTC, rancerenly commented on src/components/theme-switcher/index.tsx
> +        <Dropdown.Item onClick={() => setTheme("light")}>
три одинаковых компонента, в которых стили, текст внутри и классы можно задать пропсы, использую цикл и какую-то константу конфиг, по которому можно пройтись и все указать

2024-11-06 13:07 UTC, mrskycriper commented on public/images/itmo-logo-dark.svg
Честно говоря удобнее работать с абсолютными путями чем высчитывать их налету для такой статики. Папка `public/` при упаковке попадает куда нужно без дополнительной возни.

2024-11-06 13:07 UTC, mrskycriper commented on src/components/theme-switcher/index.tsx
> +        <Dropdown.Item onClick={() => setTheme("light")}>
Сделал.

2024-11-06 13:08 UTC, mrskycriper commented on src/components/theme-switcher/index.tsx
> +    const value = localStorage.getItem("color-theme");
Переработал полностью.

2024-11-06 13:09 UTC, mrskycriper commented on src/components/footer/index.tsx
> +function Footer() {
Единого стиля для компонентов нет, но описание через `function` применяется в документации и является более принятым.

2024-11-06 13:09 UTC, mrskycriper commented on src/components/theme-switcher/index.tsx
> +function isOfTheme(value: string): value is Theme {
Переработал полностью.

2024-11-06 13:09 UTC, mrskycriper commented on src/components/theme-switcher/index.tsx
> +  return ["auto", "light", "dark"].includes(value);
Переработал полностью.

2024-11-06 13:09 UTC, mrskycriper commented on src/components/theme-switcher/index.tsx
> +          style={{ margin: "0 1px", width: "16px" }}
Переработал полностью.

2024-11-06 13:09 UTC, mrskycriper commented on src/components/theme-switcher/index.tsx
> +    switch (theme) {
Переработал полностью.

2024-11-06 13:47 UTC, rancerenly requested changes

2024-11-06 13:47 UTC, rancerenly commented on src/components/theme-switcher/utils.ts
> +      return THEME_ICONS[Theme.Auto];
тут можно вообще без свича

```typescript
export const getThemeIcon = (theme: Theme): string => {
    return THEME_ICONS[theme];
}
```

2024-11-06 13:47 UTC, rancerenly commented on src/components/theme-switcher/types.ts
> +export enum Theme {
Можно оба енама сделать как Type

2024-11-06 13:47 UTC, rancerenly commented on src/components/theme-switcher/types.ts
> +export enum ColorScheme {
```typescript
export type ColorScheme = 'light' | 'dark';
```

2024-11-06 13:47 UTC, rancerenly commented on src/components/theme-switcher/utils.ts
> +export const getThemeIcon = (theme: Theme): string => {
тут свичи и мапа некорректно выглядят
можно полностью уйти от свичей

```typescript
export const getThemeIcon = (theme: Theme): string => {
    return THEME_ICONS[theme];
}
```

можно вот так вот сделать, если у тебя в константе в качестве ключа будет либо enum, либо ты enum как type переделаешь

v1:
```typescript
export type Theme = 'auto' | 'light' | 'dark';

export const THEME_ICONS: Record<Theme, string> = {
    auto: 'bi-circle-half',
    light: 'bi-sun-fill',
    dark: 'bi-moon-stars-fill',
};

export const getThemeIcon = (theme: Theme): string => {
    return THEME_ICONS[theme];
};
```

v2: 

```typescript

export enum Theme {
    Auto = 'auto',
    Light = 'light',
    Dark = 'dark',
}

export const THEME_ICONS: Record<Theme, string> = {
    [Theme.Auto]: 'bi-circle-half',
    [Theme.Light]: 'bi-sun-fill',
    [Theme.Dark]: 'bi-moon-stars-fill',
};

export const getThemeIcon = (theme: Theme): string => {
    return THEME_ICONS[theme];
};
```

2024-11-06 15:24 UTC, rancerenly approved these changes

2024-11-06 15:24 UTC, merged